name: blog
description: 博时代App是一款技术博客咨询类软件, 项目有登录、注册、项目、积分排行榜、问题反馈、广场、问答、搜索、技术类项目、收藏、历史、个人信息、关于、分享等模块。
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 添加国际化依赖
  flutter_localizations:
    sdk: flutter
  # 本地化 https://pub.flutter-io.cn/packages/intl
  # intl: ^0.17.0
  # GetX状态管理框架 https://pub.flutter-io.cn/packages/get
  get: ^4.6.1
  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6
  # 网络检测 https://pub.flutter-io.cn/packages/connectivity_plus
  connectivity_plus: ^2.3.0
  # 数据持久化之键值存储 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.13
  # lottie动画 https://pub.flutter-io.cn/packages/lottie
  lottie: ^1.3.0
  # Toast + loading https://pub.flutter-io.cn/packages/flutter_easyloading
  flutter_easyloading: ^3.0.3
  # 上拉刷新、下拉加载 https://pub.flutter-io.cn/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # 加载SVG图片 https://pub.flutter-io.cn/packages/flutter_svg
  flutter_svg: ^1.0.3
  # 轮播图 https://pub.flutter-io.cn/packages/card_swiper
  card_swiper: ^2.0.3
  # 调用分享平台 https://pub.flutter-io.cn/packages/share_plus
  share_plus: ^4.0.4
  # Webview工具 https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^3.0.2
  # 应用内部浏览器 https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.1.0
  # 加载html标签 https://pub.flutter-io.cn/packages/flutter_html
  flutter_html: ^3.0.0-alpha.3
  # 链家组件库 https://pub.flutter-io.cn/packages/bruno
  # bruno: ^2.1.1
  # HTML字符串转义 https://pub.flutter-io.cn/packages/html
  html: ^0.15.0
  # 权限申请框架 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^9.2.0
  # 图片保存到本地 https://pub.flutter-io.cn/packages/image_gallery_saver
  image_gallery_saver: ^1.7.1
  # 文件路径管理工具类 https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.9
  # 读取相册 https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^0.8.5
  # 微信图片选择器 https://pub.flutter-io.cn/packages/wechat_assets_picker
  wechat_assets_picker: ^7.1.0
  # 微信相机选择器 https://pub.flutter-io.cn/packages/wechat_camera_picker
  wechat_camera_picker: ^3.0.4
  # shared_preferences plugin util https://pub.dev/packages/sp_util
  sp_util: ^2.0.3

  # iOS style icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  rename_app: ^1.1.0

flutter:
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

flutter_intl:
  enabled: true