# This file contains the fastlane.tools configuration
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "上传iOSApp到fir.im平台"

  # 打包上传执行的命令名: fastlane fir
  lane :fir do
    
    # 如果你没有申请adhoc证书，sigh会自动帮你申请，并且添加到Xcode里
    #   sigh(adhoc: true)

    scheme = "Runner"
    ipa_dir  = "./fastlane_build/" + Time.new.strftime('%Y-%m-%d')
    ipa_name = 'Runner_Fir.ipa'
  
      
    # 以下两个action来自fastlane-plugin-versioning，
    # 第一个递增 Build，第二个设定Version。
    # 如果你有多个target，就必须指定target的值，否则它会直接找找到的第一个plist修改
    # 在这里我建议每一个打的包的Build都要不一样，这样crash了拿到日志，可以对应到ipa上
    increment_build_number_in_plist(
        target: scheme,
        build_number: '2'
    )
    increment_version_number_in_plist(
        target: scheme,
        version_number: '1.0.1'
    )
    # gym用来编译ipa
    gym(
      workspace: scheme + ".xcworkspace",
        scheme: scheme,
        export_options: {
        method: "ad-hoc", # 指定打包方式 ["app-store", "ad-hoc", "package", "enterprise", "development", "developer-id"]
        teamID: "25ZE6TVB9T" # 在developer网站获取
      },
        xcargs: "-allowProvisioningUpdates",
        # output_directory: ipa_dir,
        # output_name: ipa_name
    )
    # 上传ipa到fir.im服务器，在fir.im获取firim_api_token
    firim(firim_api_token: "941d301db7eee430a7d94f0e33edcee8")  # token 在fir 上查看。

  end
end
